import { test, expect } from '@playwright/test';

test('prueba de preventivo y carga de documento', async ({ page }) => {
  await page.goto('http://localhost:8000/');
  await page.getByRole('textbox', { name: 'Usuario (*)' }).click();
  await page.getByRole('textbox', { name: 'Usuario (*)' }).fill('toba');
  await page.getByRole('textbox', { name: 'Usuario (*)' }).press('Tab');
  await page.getByRole('textbox', { name: 'Clave (*)' }).fill('toba1234');
  await page.getByRole('button', { name: 'Ingresar' }).click();
  await page.getByRole('link', { name: 'Close' }).click();
  await page.getByText('Preventivos', { exact: true }).click();
  await page.getByRole('link', { name: 'Nuevo preventivo' }).click();
  await page.locator('#cont_ef_form_103000787_formulariofecha_hecho').getByRole('img', { name: '...' }).click();
  await page.getByRole('link', { name: '19' }).click();
  await page.locator('#ef_form_103000787_formularionum_sumario').click();
  await page.locator('#ef_form_103000787_formularionum_sumario').fill('1.2345');
  await page.getByRole('cell', { name: 'Origen (*) Comisaría Fiscalía Fecha de entrada (*) 19/03/2026 ... Fecha del hecho 19/03/2026 ... Tipo preventivo (*) Sumario Expediente Tipo sumario (*) Penal Contravencional Número sumario (*) 12.345 Año (*) 2026 Provincia Misiones Localidad Comisaría Designación (*) Observaciones', exact: true }).getByPlaceholder('Texto a filtrar.').click();
  await page.getByRole('cell', { name: 'Origen (*) Comisaría Fiscalía Fecha de entrada (*) 19/03/2026 ... Fecha del hecho 19/03/2026 ... Tipo preventivo (*) Sumario Expediente Tipo sumario (*) Penal Contravencional Número sumario (*) 12.345 Año (*) 2026 Provincia Misiones Localidad Comisaría Designación (*) Observaciones', exact: true }).getByPlaceholder('Texto a filtrar.').fill('posadas');
  await page.getByText('Posadas', { exact: true }).click();
  await page.locator('#ef_form_103000787_formularioid_comisaria').selectOption('6');
  await page.getByRole('textbox', { name: 'Designación (*)' }).click();
  await page.getByRole('textbox', { name: 'Designación (*)' }).fill('preventivo de prueba');
  await page.getByRole('textbox', { name: 'Observaciones' }).click();
  await page.getByRole('textbox', { name: 'Observaciones' }).fill('observaciones varias');
  await page.getByRole('cell', { name: 'Delitos   Delito(*)', exact: true }).getByPlaceholder('Texto a filtrar.').click();
  await page.getByRole('cell', { name: 'Delitos   Delito(*)', exact: true }).getByPlaceholder('Texto a filtrar.').fill('hurto');
  await page.getByText('Hurto Agravado (art. 163 bis').click();
  await page.getByRole('button', { name: 'Guardar denuncia' }).click();
  await page.getByRole('button', { name: 'Documentación externa' }).click();
  await page.getByRole('button', { name: 'Agregar documento' }).click();
  await page.getByRole('button', { name: 'Documento (*)' }).click();
  await page.getByRole('button', { name: 'Documento (*)' }).setInputFiles('pdf-sample_0.pdf');
  await page.getByRole('textbox', { name: 'Observaciones' }).click();
  await page.getByRole('textbox', { name: 'Observaciones' }).fill('documento de prueba');
  await page.getByLabel('Tipo documento (*)').selectOption('1');
  await page.getByRole('button', { name: 'Agregar documento' }).click();
  await page.getByRole('button', { name: 'Volver' }).click();
  await expect(page.locator('#barra_superior')).toContainText('Ficha de preventivos');
  await expect(page.locator('#barra_superior')).toContainText('Ficha de preventivos');
});